### ISSUE TITLE
Is neighborhood vs super neighborhood a required choice?

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-collect#15]
The naming form yells at me if I leave any other option blank, but not this one. Is that correct? And if so, assuming it defaults to neighborhood in this case, should that radio button be pre-selected?

**Comment by awoodruff** [comment]
Or maybe it is in fact pre-checked... in which case the bug is that at some point it did not show up that way for me.

**Comment by awoodruff** [comment]
Okay, update here. It looks like Neighborhood is pre-checked the first time, but on subsequently drawn neighborhoods both radio boxes are unchecked by default.

**Comment by davidheyman** [comment]
Let's set the behavior here like the others. Start unchecked and require a
response before submitting.
