### ISSUE TITLE
border-radius on map buttons

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-collect#18]
This is pretty small and hard to spot, but it looks like the border radius of buttons and their contents may not quite be matching up. If you look closely at the hover state below, you can see some corners sticking out.
![screen shot 2015-03-18 at 12 03 53 pm](https://cloud.githubusercontent.com/assets/3533462/6713319/e04742de-cd67-11e4-8e61-1bb7dcd17ea5.png)

**Comment by kingfisher13** [comment]
This seems to be a problem with Bootstrap - specifically the interplay of the box-shadow and the border-radius. Getting rid of the box-shadow makes it look fine, but of course is slightly harder to see the buttons.

**Comment by bcsheesley** [comment]
If you do end up ditching the box-shadow (or, even if you find a way to keep it), a border-color of #999 makes them easier to see.
![shadow](https://cloud.githubusercontent.com/assets/4501388/6720315/efa6cbf0-cd8f-11e4-921d-a6b1828b8647.png)
![no_shadow](https://cloud.githubusercontent.com/assets/4501388/6720317/f20676d4-cd8f-11e4-9143-4efcd8d55406.png)
