### ISSUE TITLE
iPad: form fields are not validated

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-collect#19]
It's possible to submit the form with empty fields. A blank name will break the confirmation thing (it just spins forever), but otherwise it will still go through.

**Comment by kingfisher13** [comment]
Apparently iOS doesn't honor the "required" field on a form. Looking into workarounds.

[CanIUse Required](http://caniuse.com/#search=required)

**Comment by kingfisher13** [comment]
Mostly done. Right now it adds error to entire form instead of just the individual elements that are wrong.

**Comment by kingfisher13** [comment]
I'm working on a solution to this. Right now the commit pops up alerts on iOS which obviously isn't great.
